version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ../2020.1_G12_Stock_Backend/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stockapp
      POSTGRES_DB: stock

  app:
    build:
      context: ../2020.1_G12_Stock_Backend/
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: yarn start
    ports:
      - "8000:8000"
    volumes:
      - ../2020.1_G12_Stock_Backend:/app/
      - /app/node_modules

  web:
    stdin_open: true
    build:
      context: ../2020.1_G12_Stock_Frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: yarn start
    volumes:
      - "/app/node_modules"
      - "../2020.1_G12_Stock_Frontend:/app"
